# -*- coding: utf-8 -*-
"""Predicting Hospital Readmission Risk and Estimated Cost for Diabetic Patients.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJZvCsRU26J7whZZP-e_9mWWvhYq0Bq4
"""

# Project: Predicting Hospital Readmission Risk and Estimated Cost for Diabetic Patients (Colab-Compatible Version)

# STEP 1: Import Libraries
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from zipfile import ZipFile
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import classification_report, roc_auc_score, mean_squared_error, r2_score, confusion_matrix, ConfusionMatrixDisplay
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

# STEP 2: Upload and Extract Dataset
from google.colab import files
uploaded = files.upload()  # Upload the ZIP file manually

zip_filename = next(iter(uploaded))
extract_path = "/content/diabetic_data_extracted"
os.makedirs(extract_path, exist_ok=True)

with ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

csv_filename = [f for f in os.listdir(extract_path) if f.endswith('.csv')][0]
file_path = os.path.join(extract_path, csv_filename)

try:
    df = pd.read_csv(file_path)
    print("Data loaded successfully from:", file_path)
    display(df.head())
except Exception as e:
    raise RuntimeError(f"Failed to read the dataset: {e}")

# STEP 3: Feature Engineering
if 'readmitted' in df.columns:
    df['readmitted_binary'] = df['readmitted'].apply(lambda x: 'YES' if x == '<30' else 'NO')
else:
    raise ValueError("Column 'readmitted' not found in dataset.")

if 'time_in_hospital' in df.columns:
    df['hospital_cost'] = df['time_in_hospital'] * 1200
else:
    raise ValueError("Column 'time_in_hospital' not found in dataset.")

categorical_features = ["gender", "race", "discharge_disposition_id"]
numerical_features = ["time_in_hospital", "num_lab_procedures", "num_medications", "number_inpatient"]

df.dropna(subset=categorical_features + numerical_features, inplace=True)

preprocessor = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="mean")),
        ("scaler", StandardScaler())
    ]), numerical_features),

    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical_features)
])

X = df[categorical_features + numerical_features]
y_class = df["readmitted_binary"]
y_reg = df["hospital_cost"]

# STEP 4: Split Data
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X, y_class, test_size=0.2, random_state=42, stratify=y_class)
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X, y_reg, test_size=0.2, random_state=42)

# STEP 5: Classification Model (Random Forest + SMOTE)
smote = SMOTE(random_state=42)
clf_pipeline = ImbPipeline([
    ("preprocessor", preprocessor),
    ("smote", smote),
    ("classifier", RandomForestClassifier(class_weight="balanced", n_estimators=200, max_depth=10, random_state=42))
])

clf_pipeline.fit(X_train_c, y_train_c)
y_pred_c = clf_pipeline.predict(X_test_c)

print("\nClassification Report:")
print(classification_report(y_test_c, y_pred_c))

try:
    print("ROC AUC Score:", roc_auc_score(pd.get_dummies(y_test_c)["YES"], pd.get_dummies(y_pred_c)["YES"]))
except Exception as e:
    print(f"ROC AUC Score cannot be computed: {e}")

cm = confusion_matrix(y_test_c, y_pred_c, labels=['NO', 'YES'])
ConfusionMatrixDisplay(cm, display_labels=['NO', 'YES']).plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# STEP 6: Regression Model (Random Forest)
reg_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42))
])

reg_pipeline.fit(X_train_r, y_train_r)
y_pred_r = reg_pipeline.predict(X_test_r)

print("\nRegression Performance:")
print("MSE:", mean_squared_error(y_test_r, y_pred_r))
print("R2 Score:", r2_score(y_test_r, y_pred_r))

plt.figure(figsize=(6, 6))
plt.scatter(y_test_r, y_pred_r, alpha=0.5, color='green')
plt.xlabel("Actual Hospital Cost")
plt.ylabel("Predicted Hospital Cost")
plt.title("Actual vs Predicted Hospital Costs")
plt.plot([y_test_r.min(), y_test_r.max()], [y_test_r.min(), y_test_r.max()], 'r--')
plt.grid(True)
plt.tight_layout()
plt.show()